'use strict';

/** Тексты окна установки и удаления. Ключи в ru и en совпадают — это проверяет тест. */
const STRINGS = {
  ru: {
    'window.title': 'Установка ModLaunch',
    'window.titleUninstall': 'Удаление ModLaunch',
    'window.min': 'Свернуть',
    'window.close': 'Закрыть',

    'welcome.title': 'Установка ModLaunch',
    'welcome.titleUpdate': 'Обновление ModLaunch',
    'welcome.lead': 'Моды для Stardew Valley, Hollow Knight, Lethal Company, Subnautica и Below Zero — в один клик.',
    'welcome.update': 'Сейчас стоит версия {from}. Она обновится до {version}, настройки и моды останутся на месте.',
    'welcome.updateLegacy': 'Здесь уже стоит ModLaunch. Он обновится до {version}, настройки и моды останутся на месте.',
    'welcome.folder': 'Папка установки',
    'welcome.change': 'Изменить',
    'welcome.desktop': 'Ярлык на рабочем столе',
    'welcome.launch': 'Запустить после установки',
    'welcome.install': 'Установить',
    'welcome.updateBtn': 'Обновить',
    'welcome.portable': 'Запустить без установки',
    'welcome.terms': 'Нажимая «{button}», вы принимаете',
    'welcome.termsLink': 'условия использования',

    'license.title': 'Условия использования',
    'license.close': 'Понятно',

    'progress.install': 'Устанавливаю ModLaunch',
    'progress.update': 'Обновляю ModLaunch',
    'step.close': 'Закрываю запущенный ModLaunch…',
    'step.clean': 'Убираю старую версию…',
    'step.copy': 'Копирую файлы',
    'step.integrate': 'Создаю ярлыки и связываю с Nexus Mods…',
    'step.done': 'Готово',
    'progress.bytes': '{done} из {total} МБ',
    'progress.hint': 'Обычно это меньше минуты. Настройки, ключ Nexus и список модов не трогаем — они лежат отдельно.',

    'done.title': 'ModLaunch установлен',
    'done.titleUpdate': 'ModLaunch обновлён до {version}',
    'done.textDesktop': 'Ярлыки — на рабочем столе и в меню «Пуск».',
    'done.textStart': 'Ярлык — в меню «Пуск».',
    'done.launch': 'Запустить ModLaunch',
    'done.launching': 'Запускаю…',
    'done.close': 'Закрыть',

    'error.title': 'Не получилось установить',
    'error.retry': 'Повторить',
    'error.back': 'Назад',
    'error.SETUP_BUSY': 'Файлы ModLaunch заняты — скорее всего, он ещё открыт. Закройте его и нажмите «Повторить».',
    'error.SETUP_ACCESS': 'Нет доступа к этой папке. Выберите другую — например, предложенную по умолчанию.',
    'error.SETUP_SPACE': 'На диске закончилось место. Освободите немного и нажмите «Повторить».',
    'error.SETUP_TARGET_FOREIGN': 'В этой папке уже лежат чужие файлы. Выберите пустую папку или вернитесь к предложенной.',
    'error.SETUP_TARGET_SELF': 'Нельзя ставить в папку, из которой запущен установщик. Выберите другую.',
    'error.SETUP_PS': 'Windows не дала записать настройки: {message}',
    'error.generic': 'Что-то пошло не так: {message}',

    'uninstall.title': 'Удалить ModLaunch?',
    'uninstall.lead': 'Программа уйдёт с компьютера. Моды, которые уже стоят в играх, останутся на месте.',
    'uninstall.wipe': 'Удалить ещё настройки, ключ Nexus и список модов',
    'uninstall.go': 'Удалить',
    'uninstall.cancel': 'Отмена',
    'uninstall.progress': 'Удаляю ModLaunch…',
    'uninstall.done': 'ModLaunch удалён',
    'uninstall.bye': 'Спасибо, что были с нами. Моды в играх остались на месте.',
    'uninstall.error': 'Не получилось удалить',
    'uninstall.hint': 'Моды, которые уже стоят в играх, остаются на месте.',
  },

  en: {
    'window.title': 'ModLaunch Setup',
    'window.titleUninstall': 'Uninstall ModLaunch',
    'window.min': 'Minimize',
    'window.close': 'Close',

    'welcome.title': 'Install ModLaunch',
    'welcome.titleUpdate': 'Update ModLaunch',
    'welcome.lead': 'Mods for Stardew Valley, Hollow Knight, Lethal Company, Subnautica and Below Zero — in one click.',
    'welcome.update': 'Version {from} is installed. It will be updated to {version}; your settings and mods stay put.',
    'welcome.updateLegacy': 'ModLaunch is already here. It will be updated to {version}; your settings and mods stay put.',
    'welcome.folder': 'Install folder',
    'welcome.change': 'Change',
    'welcome.desktop': 'Desktop shortcut',
    'welcome.launch': 'Launch when finished',
    'welcome.install': 'Install',
    'welcome.updateBtn': 'Update',
    'welcome.portable': 'Run without installing',
    'welcome.terms': 'By clicking “{button}” you accept the',
    'welcome.termsLink': 'terms of use',

    'license.title': 'Terms of use',
    'license.close': 'Got it',

    'progress.install': 'Installing ModLaunch',
    'progress.update': 'Updating ModLaunch',
    'step.close': 'Closing the running ModLaunch…',
    'step.clean': 'Removing the old version…',
    'step.copy': 'Copying files',
    'step.integrate': 'Creating shortcuts and linking Nexus Mods…',
    'step.done': 'Done',
    'progress.bytes': '{done} of {total} MB',
    'progress.hint': 'Usually under a minute. Settings, the Nexus key and the mod list are kept — they live separately.',

    'done.title': 'ModLaunch is installed',
    'done.titleUpdate': 'ModLaunch is updated to {version}',
    'done.textDesktop': 'Shortcuts are on the desktop and in the Start menu.',
    'done.textStart': 'The shortcut is in the Start menu.',
    'done.launch': 'Launch ModLaunch',
    'done.launching': 'Launching…',
    'done.close': 'Close',

    'error.title': 'Installation failed',
    'error.retry': 'Try again',
    'error.back': 'Back',
    'error.SETUP_BUSY': 'ModLaunch files are busy — it is probably still running. Close it and click “Try again”.',
    'error.SETUP_ACCESS': 'No access to this folder. Pick another one, for example the suggested default.',
    'error.SETUP_SPACE': 'The disk is full. Free some space and click “Try again”.',
    'error.SETUP_TARGET_FOREIGN': 'This folder already contains other files. Pick an empty folder or go back to the suggested one.',
    'error.SETUP_TARGET_SELF': 'You cannot install into the folder the installer runs from. Pick another one.',
    'error.SETUP_PS': 'Windows refused to save the settings: {message}',
    'error.generic': 'Something went wrong: {message}',

    'uninstall.title': 'Uninstall ModLaunch?',
    'uninstall.lead': 'The program will be removed. Mods already installed into your games stay where they are.',
    'uninstall.wipe': 'Also delete settings, the Nexus key and the mod list',
    'uninstall.go': 'Uninstall',
    'uninstall.cancel': 'Cancel',
    'uninstall.progress': 'Uninstalling ModLaunch…',
    'uninstall.done': 'ModLaunch is uninstalled',
    'uninstall.bye': 'Thanks for using it. Mods in your games stay in place.',
    'uninstall.error': 'Could not uninstall',
    'uninstall.hint': 'Mods already installed into your games stay in place.',
  },
};

function pickLanguage(locale) {
  return String(locale ?? '').toLowerCase().startsWith('ru') ? 'ru' : 'en';
}

module.exports = { STRINGS, pickLanguage };
